code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension christian-kohler.path-intellisense
code --install-extension cpylua.language-postcss
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-environment-manager
code --install-extension dotjoshjohnson.xml
code --install-extension dustypomerleau.rust-syntax
code --install-extension fabiospampinato.vscode-diff
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.theme-brogrammer
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension hedinne.popping-and-locking-vscode
code --install-extension idleberg.hopscotch
code --install-extension kamikillerto.vscode-colorize
code --install-extension marp-team.marp-vscode
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-attrs-sorter
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.flake8
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.theme-markdownkit
code --install-extension ms-vscode.wordcount
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension patbenatar.advanced-new-file
code --install-extension robbowen.synthwave-vscode
code --install-extension robertoachar.vscode-essentials-snippets
code --install-extension rust-lang.rust-analyzer
code --install-extension sensourceinc.vscode-sql-beautify
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension tomoki1207.pdf
code --install-extension tyriar.lorem-ipsum
code --install-extension tyriar.sort-lines
code --install-extension vadimcn.vscode-lldb
code --install-extension waderyan.gitblame
code --install-extension wholroyd.jinja
code --install-extension yandeu.five-server
code --install-extension yzhang.markdown-all-in-one
code --install-extension zaferayan.lorem-picsum
code --install-extension zardoy.fix-all-json
