code --install-extension antfu.browse-lite
code --install-extension antfu.vite
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension bcherny.better-asciidoc-vscode
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cpylua.language-postcss
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-diff
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Brogrammer
code --install-extension Gruntfuggly.todo-tree
code --install-extension hedinne.popping-and-locking-vscode
code --install-extension hollowtree.vue-snippets
code --install-extension HookyQR.beautify
code --install-extension idleberg.hopscotch
code --install-extension kamikillerto.vscode-colorize
code --install-extension marp-team.marp-vscode
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-attrs-sorter
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.Theme-MarkdownKit
code --install-extension ms-vscode.wordcount
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension mubaidr.vuejs-extension-pack
code --install-extension octref.vetur
code --install-extension patbenatar.advanced-new-file
code --install-extension RobbOwen.synthwave-vscode
code --install-extension robertoachar.vscode-essentials-snippets
code --install-extension robinbentley.sass-indented
code --install-extension rust-lang.rust
code --install-extension rust-lang.rust-analyzer
code --install-extension sdras.vue-vscode-snippets
code --install-extension sensourceinc.vscode-sql-beautify
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension tomoki1207.pdf
code --install-extension Tyriar.lorem-ipsum
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension Vue.volar
code --install-extension Vue.vscode-typescript-vue-plugin
code --install-extension waderyan.gitblame
code --install-extension wholroyd.jinja
code --install-extension yandeu.five-server
code --install-extension yzhang.markdown-all-in-one
code --install-extension ZaferAYAN.lorem-picsum
